# Generated by Django 2.1.1 on 2018-09-29 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtreembackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='children',
            field=models.ManyToManyField(related_name='_node_children_+', to='xtreembackend.Node'),
        ),
        migrations.AddField(
            model_name='node',
            name='parents',
            field=models.ManyToManyField(related_name='_node_parents_+', to='xtreembackend.Node'),
        ),
    ]
