# Generated by Django 2.1.1 on 2018-09-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtreembackend', '0003_auto_20180929_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to='xtreembackend.Node'),
        ),
    ]
