# Generated by Django 2.1.1 on 2018-09-30 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtreembackend', '0004_auto_20180930_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='node_type',
            field=models.CharField(choices=[('general', 'general'), ('topic', 'topic'), ('fact', 'fact'), ('pro_arg', 'pro_arg'), ('con_arg', 'con_arg'), ('question', 'question'), ('problem', 'problem'), ('idea', 'idea'), ('aim', 'aim'), ('region', 'region')], default='general', max_length=20),
        ),
    ]
