# Generated by Django 2.1.2 on 2019-04-13 16:44

from django.db import migrations, models
import django.db.models.deletion

join_table_sql = """
INSERT INTO xtreembackend_node_x_link (referrer_id, referree_id)
SELECT from_node_id, to_node_id
FROM xtreembackend_node_parents
"""

class Migration(migrations.Migration):

    dependencies = [
        ('xtreembackend', '0006_node_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'xtreembackend_node_x_link',
            },
        ),
        migrations.AlterField(
            model_name='node',
            name='content',
            field=models.TextField(blank=True, max_length=65535),
        ),
        migrations.AddField(
            model_name='link',
            name='referree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referredFrom', to='xtreembackend.Node'),
        ),
        migrations.AddField(
            model_name='link',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refersTo', to='xtreembackend.Node'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('referrer', 'referree')},
        ),
        migrations.RunSQL(join_table_sql),
    ]
