# Generated by Django 2.1.2 on 2019-04-13 17:05

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('xtreembackend', '0008_remove_node_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', through='xtreembackend.Link', to='xtreembackend.Node'),
        ),
    ]
