# Generated by Django 2.1.2 on 2019-04-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtreembackend', '0009_node_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
