# Generated by Django 2.1.2 on 2019-04-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtreembackend', '0010_link_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='referree',
            new_name='from_node',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='referrer',
            new_name='to_node',
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('to_node', 'from_node')},
        ),
    ]
