# Generated by Django 2.1.2 on 2020-10-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtreembackend', '0012_auto_20190416_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('general', 'general'), ('pro_arg', 'pro_arg'), ('con_arg', 'con_arg')], default='general', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('type', 'to_node', 'from_node')},
        ),
    ]
