# Generated by Django 2.1.2 on 2021-05-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtreembackend', '0013_auto_20201007_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='author',
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('general', 'general'), ('topic', 'topic'), ('fact', 'fact'), ('pro_arg', 'pro_arg'), ('con_arg', 'con_arg'), ('question', 'question'), ('problem', 'problem'), ('idea', 'idea'), ('aim', 'aim'), ('region', 'region')], default='general', max_length=20),
        ),
    ]
